FROM node:22-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json turbo.json ./
COPY apps/backend/package.json apps/backend/
COPY packages/shared-types/package.json packages/shared-types/

COPY apps/backend ./apps/backend
COPY packages/shared-types ./packages/shared-types

RUN pnpm install --frozen-lockfile
WORKDIR /app/apps/backend
RUN pnpm build

FROM node:22-alpine AS runtime
WORKDIR /app/apps/backend
RUN npm install -g pnpm

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json turbo.json /app/
COPY apps/backend/package.json /app/apps/backend/
COPY packages/shared-types/package.json /app/packages/shared-types/

RUN cd /app && pnpm install --frozen-lockfile --prod --filter backend

COPY --from=builder /app/apps/backend/dist ./dist
EXPOSE 3000
CMD ["node", "dist/index.js"]